sudo:  required

language:  cpp

services:
 - docker

#env:
# - 

before_install:
 - cd test/ci/docker
# - docker pull test/ci/docker/Dockerfile.ngtf-bridge-ci
# - DOCKER COMMAND HERE

install: true

script:
 - make-docker-ngtf-bridge-ci.sh travis_ci_image

branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
