sudo:  required

language:  cpp

services:
 - docker

env:
 - TF_NG_MODEL_DATASET=resnet20-cifar10 
 - TF_NG_EPOCHS=1

before_install:
 - cd test/ci/docker
# - sudo apt-get install wget
 - docker build -t travis_ci_image -f Dockerfile.ngtf-bridge-ci .

install: true

script:
 #- ./make-docker-ngtf-bridge-ci.sh travis_ci_image
 - ./docker-run-ngtf-bridge-validation-test.sh travis_ci_test



branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
