sudo:  required

language:  cpp

services:
 - docker

#env:
 #- TF_NG_MODEL_DATASET=resnet20-cifar10 
 #- TF_NG_EPOCHS=1
 - NGRAPH_VLOG_LEVEL=0

before_install:
 - pwd
 - sudo -E apt-get install python-numpy python-dev python-pip python-wheel
 - pwd
 - git clone --depth=50 https://github.com/NervanaSystems/ngraph-tensorflow.git /home/travis/build/ngraph-tensorflow
 - pwd
 - sudo -E apt-get install python-virtualenv
 - pwd
 - virtualenv --system-site-packages ~/tensorflow
 - pwd
 - source ~/tensorflow/bin/activate
 - pwd
 - easy_install -U pip

 - pwd
 - ls ..

 - pip install --upgrade tensorflow
 - cd ngraph-tensorflow
 - git checkout ngraph-tensorflow-preview-0

 - cd test/ci/docker
 - docker build -t travis_ci_image -f Dockerfile.ngtf-bridge-ci .
 - cd ..

install: true

script:
# This is the long run.
# - ./docker-run-ngtf-bridge-validation-test.sh travis_ci_test
 - ./run-unit-tests.sh
# - ./run-premerge-ci-checks.sh /home/travis/build/ngraph-tensorflow


branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
