sudo:  required

language:  cpp

services:
 - docker

#env:
 #- TF_NG_MODEL_DATASET=resnet20-cifar10 
 #- TF_NG_EPOCHS=1

before_install:
 - git clone --depth=50 https://github.com/NervanaSystems/ngraph-tensorflow.git /home/travis/build/ngraph-tensorflow
 - cd test/ci/docker
 - docker build -t travis_ci_image -f Dockerfile.ngtf-bridge-ci .
 - cd ..

install: true

script:
# This is the long run.
# - ./docker-run-ngtf-bridge-validation-test.sh travis_ci_test
 - ./run-unit-tests.sh
# - ./run-premerge-ci-checks.sh /home/travis/build/ngraph-tensorflow


branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
