sudo:  required

language:  cpp

services:
 - docker

#env:
 #- TF_NG_MODEL_DATASET=resnet20-cifar10 
 #- TF_NG_EPOCHS=1

before_install:
 - git clone https://github.com/NervanaSystems/ngraph-tensorflow.git
 - cd test/ci/docker
# - sudo apt-get install wget
 - docker build -t travis_ci_image -f Dockerfile.ngtf-bridge-ci .
 - cd ..
 - ls /home/travis/buld/

install: true

script:
 #- ./make-docker-ngtf-bridge-ci.sh travis_ci_image
# This is the long run.
 #- ./docker-run-ngtf-bridge-validation-test.sh travis_ci_test
 - ./run-premerge-ci-checks.sh



branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
