sudo:  required

language:  cpp

services:
 - docker

#env:
# - 

before_install:
 - cd test/ci/docker
# - sudo apt-get install wget
 - docker build -t travis_ci_image -f Dockerfile.ngtf-bridge-ci

install: true

script:
 #- ./make-docker-ngtf-bridge-ci.sh travis_ci_image


branches:
 only:
#  - "master"
  - "kims_ngraph_1666"
